export const CREATE_BOOKING_SUCCESS="CREATE_BOOKING_SUCCESS";
export const CREATE_BOOKING_FAILURE="CREATE_BOOKING_FAILURE";
export const CREATE_BOOKING_REQUEST="CREATE_BOOKING_REQUEST";

export const GET_BOOKING_SUCCESS="GET_BOOKING_SUCCESS";
export const GET_BOOKING_FAILURE="GET_BOOKING_FAILURE";
export const GET_BOOKING_REQUEST="GET_BOOKING_REQUEST";

export const GET_HOST_BOOKINGS_SUCCESS="GET_HOST_BOOKINGS_SUCCESS";
export const GET_HOST_BOOKINGS_FAILURE="GET_HOST_BOOKINGS_FAILURE";
export const GET_HOST_BOOKINGS_REQUEST="GET_HOST_BOOKINGS_REQUEST";

export const GET_BOOKINGS_BY_ID_REQUEST = "GET_BOOKINGS_BY_ID_REQUEST";
export const GET_BOOKINGS_BY_ID_SUCCESS = "GET_BOOKINGS_BY_ID_SUCCESS";
export const GET_BOOKINGS_BY_ID_FAILURE = "GET_BOOKINGS_BY_ID_FAILURE";

export const GET_BOOKINGS_ID_REQUEST = "GET_BOOKINGS_BY_ID_REQUEST";
export const GET_BOOKINGS_ID_SUCCESS = "GET_BOOKINGS_BY_ID_SUCCESS";
export const GET_BOOKINGS_ID_FAILURE = "GET_BOOKINGS_BY_ID_FAILURE";

export const GET_DELETE_BOOKING_SUCCESS="GET_DELETE_BOOKING_SUCCESS";
export const GET_DELETE_BOOKING_FAILURE="GET_DELETE_BOOKING_FAILURE";
export const GET_DELETE_BOOKING_REQUEST="GET_DELETE_BOOKING_REQUEST";

export const GET_ALL_BOOKINGS_REQUEST = "GET_ALL_BOOKINGS_REQUEST";
export const GET_ALL_BOOKINGS_SUCCESS = "GET_ALL_BOOKINGS_SUCCESS";
export const GET_ALL_BOOKINGS_FAIL = "GET_ALL_BOOKINGS_FAIL";


// ===============================
// MANAGER BOOKING ACTIONS
// ===============================

export const BOOKING_ACCEPT_REQUEST = "BOOKING_ACCEPT_REQUEST";
export const BOOKING_ACCEPT_SUCCESS = "BOOKING_ACCEPT_SUCCESS";
export const BOOKING_ACCEPT_FAIL = "BOOKING_ACCEPT_FAIL";

export const BOOKING_REJECT_REQUEST = "BOOKING_REJECT_REQUEST";
export const BOOKING_REJECT_SUCCESS = "BOOKING_REJECT_SUCCESS";
export const BOOKING_REJECT_FAIL = "BOOKING_REJECT_FAIL";

export const BOOKING_ASSIGN_ROOM_REQUEST = "BOOKING_ASSIGN_ROOM_REQUEST";
export const BOOKING_ASSIGN_ROOM_SUCCESS = "BOOKING_ASSIGN_ROOM_SUCCESS";
export const BOOKING_ASSIGN_ROOM_FAIL = "BOOKING_ASSIGN_ROOM_FAIL";

export const BOOKING_CHECKIN_REQUEST = "BOOKING_CHECKIN_REQUEST";
export const BOOKING_CHECKIN_SUCCESS = "BOOKING_CHECKIN_SUCCESS";
export const BOOKING_CHECKIN_FAIL = "BOOKING_CHECKIN_FAIL";

export const BOOKING_CHECKOUT_REQUEST = "BOOKING_CHECKOUT_REQUEST";
export const BOOKING_CHECKOUT_SUCCESS = "BOOKING_CHECKOUT_SUCCESS";
export const BOOKING_CHECKOUT_FAIL = "BOOKING_CHECKOUT_FAIL";



