export const ATTENDANCE_CHECKIN_REQUEST = "ATTENDANCE_CHECKIN_REQUEST";
export const ATTENDANCE_CHECKIN_SUCCESS = "ATTENDANCE_CHECKIN_SUCCESS";
export const ATTENDANCE_CHECKIN_FAIL = "ATTENDANCE_CHECKIN_FAIL";

export const ATTENDANCE_CHECKOUT_REQUEST = "ATTENDANCE_CHECKOUT_REQUEST";
export const ATTENDANCE_CHECKOUT_SUCCESS = "ATTENDANCE_CHECKOUT_SUCCESS";
export const ATTENDANCE_CHECKOUT_FAIL = "ATTENDANCE_CHECKOUT_FAIL";

export const ATTENDANCE_LIST_REQUEST = "ATTENDANCE_LIST_REQUEST";
export const ATTENDANCE_LIST_SUCCESS = "ATTENDANCE_LIST_SUCCESS";
export const ATTENDANCE_LIST_FAIL = "ATTENDANCE_LIST_FAIL";