export const CHATBOT_ADD_USER_MESSAGE = "CHATBOT_ADD_USER_MESSAGE";

export const CHATBOT_REQUEST = "CHATBOT_REQUEST";
export const CHATBOT_SUCCESS = "CHATBOT_SUCCESS";
export const CHATBOT_FAIL = "CHATBOT_FAIL";

export const CHATBOT_RESET = "CHATBOT_RESET";
