export const CREATE_PAYMENT_REQUEST="CREATE_PAYMENT_REQUEST";
export const CREATE_PAYMENT_SUCCESS="CREATE_PAYMENT_SUCCESS";
export const CREATE_PAYMENT_FAILURE="CREATE_PAYMENT_FAILURE";

export const UPDATE_PAYMENT_REQUEST="UPDATE_PAYMENT_REQUEST";
export const UPDATE_PAYMENT_SUCCESS="UPDATE_PAYMENT_SUCCESS";
export const UPDATE_PAYMENT_FAILURE="UPDATE_PAYMENT_FAILURE";

export const RAZORPAY_REDIRECT_REQUEST = "RAZORPAY_REDIRECT_REQUEST";
export const RAZORPAY_REDIRECT_SUCCESS = "RAZORPAY_REDIRECT_SUCCESS";
export const RAZORPAY_REDIRECT_FAIL = "RAZORPAY_REDIRECT_FAIL";
export const RAZORPAY_REDIRECT_RESET = "RAZORPAY_REDIRECT_RESET";
// ================================
// ✅ HOST EARNINGS
// ================================
export const HOST_EARNINGS_REQUEST = "HOST_EARNINGS_REQUEST";
export const HOST_EARNINGS_SUCCESS = "HOST_EARNINGS_SUCCESS";
export const HOST_EARNINGS_FAIL = "HOST_EARNINGS_FAIL";

// src/state/payment/ActionType.js

export const VERIFY_PAYMENT_REQUEST = "VERIFY_PAYMENT_REQUEST";
export const VERIFY_PAYMENT_SUCCESS = "VERIFY_PAYMENT_SUCCESS";
export const VERIFY_PAYMENT_FAILURE = "VERIFY_PAYMENT_FAILURE";