export const CREATE_REVIEW_REQUEST = "CREATE_REVIEW_REQUEST";
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const CREATE_REVIEW_FAIL = "CREATE_REVIEW_FAIL";

export const GET_LISTING_REVIEWS_REQUEST = "GET_LISTING_REVIEWS_REQUEST";
export const GET_LISTING_REVIEWS_SUCCESS = "GET_LISTING_REVIEWS_SUCCESS";
export const GET_LISTING_REVIEWS_FAIL = "GET_LISTING_REVIEWS_FAIL";

export const GET_ALL_REVIEWS_REQUEST = "GET_ALL_REVIEWS_REQUEST";
export const GET_ALL_REVIEWS_SUCCESS = "GET_ALL_REVIEWS_SUCCESS";
export const GET_ALL_REVIEWS_FAIL = "GET_ALL_REVIEWS_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";

export const RESPOND_REVIEW_REQUEST = "RESPOND_REVIEW_REQUEST";
export const RESPOND_REVIEW_SUCCESS = "RESPOND_REVIEW_SUCCESS";
export const RESPOND_REVIEW_FAIL = "RESPOND_REVIEW_FAIL";