// ROOM ACTION TYPES

// CREATE ROOM
export const CREATE_ROOM_REQUEST = "CREATE_ROOM_REQUEST";
export const CREATE_ROOM_SUCCESS = "CREATE_ROOM_SUCCESS";
export const CREATE_ROOM_FAILURE = "CREATE_ROOM_FAILURE";

// GET ALL ROOMS
export const GET_ALL_ROOMS_REQUEST = "GET_ALL_ROOMS_REQUEST";
export const GET_ALL_ROOMS_SUCCESS = "GET_ALL_ROOMS_SUCCESS";
export const GET_ALL_ROOMS_FAILURE = "GET_ALL_ROOMS_FAILURE";

// GET ROOMS BY HOTEL
export const GET_ROOMS_BY_HOTEL_REQUEST = "GET_ROOMS_BY_HOTEL_REQUEST";
export const GET_ROOMS_BY_HOTEL_SUCCESS = "GET_ROOMS_BY_HOTEL_SUCCESS";
export const GET_ROOMS_BY_HOTEL_FAILURE = "GET_ROOMS_BY_HOTEL_FAILURE";

// GET ROOM BY ID
export const GET_ROOM_BY_ID_REQUEST = "GET_ROOM_BY_ID_REQUEST";
export const GET_ROOM_BY_ID_SUCCESS = "GET_ROOM_BY_ID_SUCCESS";
export const GET_ROOM_BY_ID_FAILURE = "GET_ROOM_BY_ID_FAILURE";

// UPDATE ROOM
export const UPDATE_ROOM_REQUEST = "UPDATE_ROOM_REQUEST";
export const UPDATE_ROOM_SUCCESS = "UPDATE_ROOM_SUCCESS";
export const UPDATE_ROOM_FAILURE = "UPDATE_ROOM_FAILURE";

// DELETE ROOM
export const DELETE_ROOM_REQUEST = "DELETE_ROOM_REQUEST";
export const DELETE_ROOM_SUCCESS = "DELETE_ROOM_SUCCESS";
export const DELETE_ROOM_FAILURE = "DELETE_ROOM_FAILURE";

// STAFF CLEAN ROOM
export const CLEAN_ROOM_REQUEST = "CLEAN_ROOM_REQUEST";
export const CLEAN_ROOM_SUCCESS = "CLEAN_ROOM_SUCCESS";
export const CLEAN_ROOM_FAILURE = "CLEAN_ROOM_FAILURE";

// ROOM SEARCH
export const ROOM_SEARCH_REQUEST = "ROOM_SEARCH_REQUEST";
export const ROOM_SEARCH_SUCCESS = "ROOM_SEARCH_SUCCESS";
export const ROOM_SEARCH_FAIL = "ROOM_SEARCH_FAIL";

export const ROOM_SEARCH_RESET = "ROOM_SEARCH_RESET";

export const ROOM_UPDATE_STATUS_REQUEST = "ROOM_UPDATE_STATUS_REQUEST";
export const ROOM_UPDATE_STATUS_SUCCESS = "ROOM_UPDATE_STATUS_SUCCESS";
export const ROOM_UPDATE_STATUS_FAILURE = "ROOM_UPDATE_STATUS_FAILURE"; 